---
- name: ec2 instance launch
  hosts: localhost
  connection: local
  tasks:
  - pip:
        name: boto
  - name: lauching ec2
    ec2:
     key_name: launchec2instance
     region: ap-south-1
     instance_type: t2.micro
     image: ami-0a74bfeb190bd404f
     wait: yes
     group: ["secondsgrp", "newsecuritygrp"]
     vpc_subnet_id: subnet-ac8565c4
     instance_tags:
      Name: WebServer
      Report: Project1
     assign_public_ip: yes
     volumes:
       - device_name: /dev/sda1
         volume_size: 15
         delete_on_termination: true
     count: 11
